### PR TITLE
Only persist users with specific LTI role

### LINKED ISSUE #1690: LTI User Persistence creates too many users
**Describe the bug**
Per Ravishel Naicker on the users list, they have 30K+ students authenticating via LTI, with each one creating a new Opencast user in the database.  The majority of these users are viewer-only users, and should not exist in the database given their permissions.  Instead a regex, or other allow-list based system should be implemented to only persist users who need to be persisted (ie, Instructor roles).

### PR DESCRIPTION
**Pull request by marwyg**
fixes #1690 

With this change, only users with specific LTI roles will be persisted. The roles can be configured in `etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg`.

### CODE REVIEW

**Comment by marwyg** [comment]
Ready for review.

**Comment by kristofkeppens** [comment]
We were having the same performance issues on our installation. We have merged this change into our own branch and can confirm that it works as expected!

**Comment by lkiesow** [comment]
We shortly discussed this on the technical meeting and thought that this could be valuable for `r/9.x` since some people have real problems with too many users. @marwyg, could you rebase this to `r/9.x` but to not break any updates by unexpectedly changing Opencast's behavior then change the default value to persist all users:

```.properties
lti.create_jpa_user_reference.roles = *
```

We can then later change the default back to lecturers only for Opencast 10.

**Comment by kristofkeppens** [comment]
@lkiesow , @marwyg we took this code already in production, since we were facing serious performance issues, but just found out that setting it to "*" does not work. Specifying the types to for instance "administrator, instructor" works fine.

**Comment by marwyg** [comment]
It was rebased to `r/9.x`. 
The default value is set to `*`, which should work now. It means that everything will be persisted. 
Leaving the configuration blank should also work. It will disable the persisting.

Its ready for review again.

File: modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java [hunk 1]
```diff
@@ -160,8 +162,8 @@
   /** concurrent attemtps */
   private Map<String, Boolean> activePersistenceTransactions = new ConcurrentHashMap<>(128);
 
-  /** Determines whether a JpaUserReference should be created on lti login */
-  private boolean createJpaUserReference = true;
+  /** Contains the LTI roles where a JpaUserReference shall be created. The default is 'instructor'. */
```
Comment (lkiesow) [inline modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java]:
```suggestion
  /** LTI roles a user must have so a JpaUserReference is created. */
```

File: etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg [hunk 2]
```diff
@@ -48,12 +48,23 @@
...
+#    lti.create_jpa_user_reference = instructor
+#  - Persist only instructors and administrators:
+#    lti.create_jpa_user_reference.roles = instructor, administrator
+#  - Persist all users:
+#    lti.create_jpa_user_reference.roles = *
+#  - No persistence:
+#    lti.create_jpa_user_reference.roles =
+#
+# Default: *
+lti.create_jpa_user_reference.roles = *
```
Comment (lkiesow) [inline etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg]: Setting a default should be unnecessary:

```suggestion
#lti.create_jpa_user_reference.roles = *
```

File: modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java [hunk 3]
```diff
@@ -237,9 +239,8 @@ protected void activate(ComponentContext cc) {
       usernameBlacklist.add(username);
     }
 
-    createJpaUserReference = BooleanUtils.toBooleanDefaultIfNull(
-      BooleanUtils.toBooleanObject(StringUtils.trimToNull((String) properties.get(CREATE_JPA_USER_REFERENCE_KEY))),
-      true);
+    ltiRolesForUserCreation = extractLtiRolesForUserCreation(
+            (String) properties.get(LTI_ROLES_TO_CREATE_JPA_USER_REFERENCES_FROM));
```
Comment (lkiesow) [inline modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java]: Actually set the default you claim to set:

```suggestion
    ltiRolesForUserCreation = extractLtiRolesForUserCreation(
            Objects.toString(properties.get(LTI_ROLES_TO_CREATE_JPA_USER_REFERENCES_FROM), "*");
```

**Review by lkiesow — CHANGES_REQUESTED** [review]
Sorry for complaining about this even more :see_no_evil: 

Subsequent 9.x releases should not break previous configurations. E.g. a 9.4 should run with a 9.0 configuration and behave the same whenever possible. With this, you have the three cases:

- `lti.create_jpa_user_reference` was not set
    - The default was `true` and the new default `*` (once it is actually set in code) behaves the same  ✓
- `lti.create_jpa_user_reference` was set to `true`
    - Is the same. The new default would make the behavior stay the same ✓
- `lti.create_jpa_user_reference` was set to `false`
    - Here, the new default would suddenly start persisting users even though you had disabled this. That's a problem.

I guess the best thing to do is to still keep the old key around for now and use something like:
```java
if (createJpaUserReference && ltiRolesForUserCreation != null && ltiRolesForUserCreation.size() > 0) {
```

File: modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java (hunk 1 above)
Comment (marwyg) [reply modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java]: The key "createJpaUserReference" is included again (default true).

File: modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java (hunk 3 above)
Comment (marwyg) [reply modules/security-lti/src/main/java/org/opencastproject/security/lti/LtiLaunchAuthenticationHandler.java]: The default (*) is set programmatically now.

**Comment by marwyg** [comment]
Now the cases look like this:

`create_jpa_user_reference` = not set (default will be used = true)
`create_jpa_user_reference.roles` = not set (default will be used *)
	**- persist everything**

`create_jpa_user_reference` = false
`create_jpa_user_reference.roles` = anything (doesn't matter)
	**- persist nothing**

`create_jpa_user_reference` = true
`create_jpa_user_reference.roles` = not set (default will be used = *)
	**- persist everything**

`create_jpa_user_reference` = true
`create_jpa_user_reference.roles` = empty string (default will be used = *)
	**- persist everything**

`create_jpa_user_reference` = true
`create_jpa_user_reference.roles` = role_a, role_b
	**- persist only users with role 'role_a' and 'role_b'**

**Review by lkiesow — APPROVED** [review]
