### PR TITLE
Fix sched event deletion - recordings endpoint

### LINKED ISSUE #4273: Scheduled event deletion though DELETE /recordings/ REST API broken
**Describe the bug**
A clear and concise description of what you see:
*When scheduling an event and later deleting it through **`DELETE /recordings/EVENT_ID`** REST endpoint, the event remains without schedule and deletion on the admin UI throws an error on the admin UI after which the event disappears from the admin UI*

**To Reproduce**
1. Go to '[stable.opencast.org](https://stable.opencast.org/admin-ng/index.html)' and login as admin.
2. Click on '+ Add event'  <br>Screenshot 2022-10-04 at 15 18 55
3. Fill a title data, click next.
4. Schedule an event at any location available, select any workflow, do not change the ACLs suggested and create the event.
5. Click the event Screenshot 2022-10-04 at 15 22 09 details button in order to find the event's UUID. 
6. Go to https://stable.opencast.org/docs.html?path=/recordings#deleterecordings-1 (? -> REST-API-Docs -> /recordings -> DELETE)
7. Enter the UUID of the event you just created and click "submit"<br>Screenshot 2022-10-04 at 15 22 54
8. **Result: Scheduling itab s gone in admin UI and the status switched from scheduled to finished. Expected: Event to be gone entirely as in older versions of Opencast.**
9. Click the red "delete" mark Screenshot 2022-10-04 at 15 24 13 next to the event and confirm.
10. See error message: "The event(s) could not be deleted."

Log:

```
2022-10-04T15:25:15,272 | INFO  | (IngestServiceImpl:632) - Created mediapackage bf6f4e87-3c42-44e1-9e2a-37e217d049b1
2022-10-04T15:25:15,307 | INFO  | (AssetManagerImpl:1262) - Creating new version 0 of media package bf6f4e87-3c42-44e1-9e2a-37e217d049b1
2022-10-04T15:25:15,316 | INFO  | (AssetManagerImpl:413) - Trigger update handlers for snapshot bf6f4e87-3c42-44e1-9e2a-37e217d049b1, version 0
2022-10-04T15:25:23,766 | WARN  | (SchedulerServiceImpl:1518) - Scheduled recording  bf6f4e87-3c42-44e1-9e2a-37e217d049b1 not found for deletion from the Elasticsearch index.
2022-10-04T15:25:23,766 | INFO  | (SchedulerRestService:506) - Event with id ' bf6f4e87-3c42-44e1-9e2a-37e217d049b1' does not exist.
2022-10-04T15:25:30,503 | INFO  | (AssetManagerImpl:870) - Firing event handlers for event bf6f4e87-3c42-44e1-9e2a-37e217d049b1, snapshot 0
2022-10-04T15:25:30,503 | INFO  | (AssetManagerImpl:876) - Firing event handlers for event bf6f4e87-3c42-44e1-9e2a-37e217d049b1
```

Screencast:

https://user-images.githubusercontent.com/2311611/193832645-7462f273-4b42-44f5-8904-70b197562994.mp4

XHR (deletion from admin UI):

Screenshot 2022-10-04 at 15 33 47
Response: 3e42c43c-af5f-4c68-b4dd-4c0908ec1325

**Environment Information**
 - Browser Firefox
 - Opencast version with minor release 12.3

### PR DESCRIPTION
**Pull request by Alaschinger**
Scheduled events will be completly deleted instead of just removing the capture agent ID when using the DELETE /recordings/ endpoint. This fixes #4273 

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

File: modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java [hunk 1]
```diff
@@ -1523,6 +1523,7 @@ private void removeSchedulingInfoFromIndex(String mediaPackageId) {
 
     try {
       index.addOrUpdateEvent(mediaPackageId, updateFunction, orgId, user);
+      index.deleteEvent(mediaPackageId, orgId);
```
Comment (geichelberger) [inline modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java]: Is only deleting the event not sufficient? Why does it have to be updated and deleted afterward?

Comment (Alaschinger) [reply modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java]: In theory it is. I really don't know why there was a step specifically keeping the event with an empty capture agent ID.

Comment (Arnei) [reply modules/scheduler-impl/src/main/java/org/opencastproject/scheduler/impl/SchedulerServiceImpl.java]: As far as I can tell, updating the event before deletion has no beneficial side-effects. Therefore I went ahead and removed the update related code. Do you agree with this change @geichelberger ?

**Review by Arnei — APPROVED** [review]
