### PR TITLE
Remove duplicated oc_workflow columns

### LINKED ISSUE #4696: Duplicate mediapackage and org id columns in oc_workflow
**Describe the bug**

In prepping #4684 I noticed that my `oc_workflow` table had a `MEDIAPACKAGEID` and `ORGANIZATIONID` column, despite those columns being properly named in `WorkflowInstance`.  These columns are always NULL.

**To Reproduce**

1. Start a 12.x or newer OC, and process anything with a fresh database

**Expected behavior**

No duplicate, empty columns

**Server environment:**
 - OS: All
 - Distribution: All
 - Installation method: Source
 - Version: 12.x+

### PR DESCRIPTION
**Pull request by gregorydlogan**
This PR prevents duplicated mp and org id columns from being created in `oc_workflow`.

Discussion questions:
- Should a migration step which *removes* these columns be added to `develop`?

Fixes #4696

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by Rillke** [comment]
greg asked for this (OC12; updated from 11)

EXPLAIN oc_workflow;

```
# Field, Type, Null, Key, Default, Extra
'id', 'bigint(20)', 'NO', 'PRI', NULL, ''
'creator_id', 'varchar(255)', 'YES', '', NULL, ''
'date_completed', 'datetime', 'YES', '', NULL, ''
'date_created', 'datetime', 'YES', '', NULL, ''
'description', 'longtext', 'YES', '', NULL, ''
'mediapackage', 'longtext', 'YES', '', NULL, ''
'mediapackage_id', 'varchar(128)', 'YES', 'MUL', NULL, ''
'organization_id', 'varchar(255)', 'YES', '', NULL, ''
'series_id', 'varchar(128)', 'YES', 'MUL', NULL, ''
'state', 'int(11)', 'YES', '', NULL, ''
'template', 'varchar(255)', 'YES', '', NULL, ''
'title', 'varchar(255)', 'YES', '', NULL, ''
```

**Comment by lkiesow** [comment]
I can test this.
As discussed on the technical meeting we should test this:

- With a migrated system
- With a fresh 12.x system

**Comment by gregorydlogan** [comment]
Further dev question: Can we move the [NamedNativeQueries](https://github.com/opencast/opencast/pull/4697/files#diff-2d8d36ea663b1e422ade0ffb36c211a5a57debf00f83c4bba20601441dde58bbL39) and [SqlResultSetMapping](https://github.com/opencast/opencast/pull/4697/files#diff-2d8d36ea663b1e422ade0ffb36c211a5a57debf00f83c4bba20601441dde58bbL46) into `WorkflowInstance`?  I'm going to guess not, or else they'd already be there, but it's worth a shot.

File: modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowIndexData.java [hunk 1]
```diff
@@ -62,8 +63,12 @@ public class WorkflowIndexData {
   @Id
   private Long id;
   private int state;
+
+  @Column(name = "mediapackage_id", length = 128) //NB: This column definition needs to match WorkflowInstance!
   private String mediaPackageId;
-  private String organizationId;
+
+  @Column(name = "organization_id") //NB: This column definition needs to match WorkflowInstance!
+  private String organizationIds;
```
Comment (mtneug) [inline modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowIndexData.java]: Why the rename of `organizationId` to `organizationIds`?

**Review by mtneug — CHANGES_REQUESTED** [review]

File: modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowIndexData.java (hunk 1 above)
Comment (gregorydlogan) [reply modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowIndexData.java]: Hah, because I was trying to figure out which variable(s) generated the offending columns and forgot to change it back in the final commit 😅

**Comment by gregorydlogan** [comment]
@lkiesow did you have a chance to test this?

File: modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java [hunk 2]
```diff
@@ -142,7 +142,7 @@ public class WorkflowInstance {
   @Column(name = "creator_id")
   private String creatorName;
 
-  @Column(name = "organization_id")
+  @Column(name = "organization_id")  //NB: This column definition needs to match WorkflowInstance!
```
Comment (JamesUoM) [inline modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowInstance.java]: note should say "... match WorkflowIndexData"
