### PR TITLE
Extended CoverImageWOH to be able to use extended and series metadata

### LINKED ISSUE #1787: The cover-image WOH can only use episode metadata
**Describe the bug**
The [cover-image WOH](https://docs.opencast.org/r/8.x/admin/#workflowoperationhandlers/coverimage-woh/) can only use episode metadata. It should be possible to access the [series metadata as well as extended metadata](https://docs.opencast.org/r/8.x/admin/#configuration/metadata/).

**Environment Information**
* Opencast 8

### PR DESCRIPTION
**Pull request by jduehring**
This PR should fix #1787 . The user can now specify the flavor of the episode and series in the workflow using the parameters `episodeFlavor` and `seriesFlavor`. If not specified `dublincore/episode` and `dublincore/series` will be used as default values. Depending on what flavor was specified, the metadata of the episode gets extracted and built into xml format **including** a field for the metadata of the corresponding series (if there is any). I did not change the names of the other fields, so there shouldn't come up any conflicts with older workflows. 
Like before all fields can be accessed in the coverimage.xsl and therefore can be included in the cover image.  

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated testing
* [ ] have a clean commit history
* [ ] have proper commit messages (title and body) for all commits
* [ ] have appropriate tags applied

### CODE REVIEW

**Comment by ebbertd** [comment]
Please also update the documentation: https://github.com/opencast/opencast/blob/develop/docs/guides/admin/docs/workflowoperationhandlers/coverimage-woh.md

File: modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java [hunk 1]
```diff
@@ -302,57 +304,87 @@ protected String loadXsl(WorkflowOperationInstance operation) throws WorkflowOpe
     }
   }
 
-  protected String getMetadataXml(MediaPackage mp) {
-    StaticMetadata metadata = getStaticMetadataService().getMetadata(mp);
+  protected String getMetadataXml(MediaPackage mp, WorkflowOperationInstance operation) {
+    //get specified episode/series flavor
+    String configuredEpisodeFlavor = StringUtils.trimToEmpty(operation.getConfiguration(EPISODE_FLAVOR));
```
Comment (lkiesow) [inline modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: This is easier than to check manually for empty values:
```suggestion
    final String configuredEpisodeFlavor = Objects.toString(StringUtils.trimToNull(operation.getConfiguration(EPISODE_FLAVOR)), "dublincore/episode);
```

File: modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java [hunk 2]
```diff
@@ -302,57 +304,87 @@ protected String loadXsl(WorkflowOperationInstance operation) throws WorkflowOpe
...
+      configuredEpisodeFlavor = "dublincore/episode";
+    }
+    if (("").equals(configuredSeriesFlavor)) {
+      configuredSeriesFlavor = "dublincore/series";
+    }
+
+    String episodeFlavorType = configuredEpisodeFlavor.split("/")[0];
+    String episodeFlavorSubtype = configuredEpisodeFlavor.split("/")[1];
+    String seriesFlavorType = configuredSeriesFlavor.split("/")[0];
+    String seriesFlavorSubtype = configuredSeriesFlavor.split("/")[1];
```
Comment (lkiesow) [inline modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: Better use

```java
MediaPackageElementFlavor.parseFlavor(flavorStr);
```
You can then access the flavor and subflavor via the flavor object's methods.
And it assures that it's a valid flavor or directly use it since you want a flavor object down below anyway.

File: modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java [hunk 3]
```diff
@@ -302,57 +304,87 @@ protected String loadXsl(WorkflowOperationInstance operation) throws WorkflowOpe
...
+
+    //Get episode metadata-catalog
+    Catalog[] catalogs = mp.
+            getCatalogs(new MediaPackageElementFlavor(episodeFlavorType, StringUtils.lowerCase(episodeFlavorSubtype)));
+
+   //load metadata-catalog
```
Comment (lkiesow) [inline modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: indentation

File: modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java [hunk 4]
```diff
@@ -302,57 +304,87 @@ protected String loadXsl(WorkflowOperationInstance operation) throws WorkflowOpe
...
-    for (Date[] period : metadata.getTemporalPeriod()) {
-      if (period[0] != null) {
-        appendXml(xml, "start", new SimpleDateFormat("YYYY-MM-dd'T'HH:mm:ss").format(period[0]));
-      }
-      if (period[1] != null) {
-        appendXml(xml, "end", new SimpleDateFormat("YYYY-MM-dd'T'HH:mm:ss").format(period[1]));
+    for (Map.Entry<EName, List<DublinCoreValue>> entry : data.entrySet()) {
+      String currentKey = entry.getKey().getLocalName();
+      switch(currentKey) {
+        case "creator": appendXml(xml, "creators", entry.getValue().get(0).getValue()); break;
```
Comment (lkiesow) [inline modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: All these fields can exist not at all or multiple times. Will this work if they do not exist? Onbly using the first is probably okay but should be documented.

Comment (wsmirnow) [reply modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: Also the order of the list isn't fixed. I guess, we have to provide all values as list.

Comment (jduehring) [reply modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: @lkiesow If they do not exist, they are not beeing added to the xml, so it should be fine. There were no issues during my tests with non existing fields. I also added a note in the documentation.

@wsmirnow You mean the order of the fields in the resulting xml should stay intact?

Comment (lkiesow) [reply modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: iirc, the order isn't guaranteed in an XML document anyway.

Comment (wsmirnow) [reply modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: I would prefer the same order. It may be technically not possible. If you put only the first value of the list, you may end up with different values each call of the handler.

Comment (lkiesow) [reply modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: Now I'm confused as well :D
The code should be deterministic, shouldn't it?
So you would get the same. You just don't get all of them.

@jduehring, what happens if you iterate e.g. over multiple creator fields and call `appendXml` every time?

Comment (jduehring) [reply modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: Not sure how to test this. What would be the easiest way to get an episode containing metadata with multiple creator fields? Should this happen when I add multiple creators via the admin-ui? So for each creator one creator field?
Currently there seems to be a bug so that this does not happen. (Probably the reason for #1224 as well)
In theory my code should currently add  the same field multiple times, which is also not ideal, i guess.

Comment (lkiesow) [reply modules/cover-image-workflowoperation/src/main/java/org/opencastproject/workflow/handler/coverimage/CoverImageWorkflowOperationHandlerBase.java]: Sorry for the late reply :see_no_evil: 

The following cURL command will ingest media with two titles (which will mostly be ignored by Opencast code and just the first is usually being used) and multiple creators (which Opencast can handle just fine… mostly):

```sh
curl -i -u admin:opencast \
  https://develop.opencast.org/ingest/addMediaPackage \
  -F 'flavor=presentation/source' \
  -F 'BODY=@sintel_trailer-1080p.mp4' \
  -F title="Title 1" \
  -F title="Title 2" \
  -F creator="Creator 1" \
  -F creator="Creator 2"
```

**Comment by lkiesow** [comment]
@jduehring, what's the current state of this. Is it ready for another review?

**Comment by gregorydlogan** [comment]
@jduehring Is this ready for further review?

**Comment by jduehring** [comment]
Sorry for the late reply. Ready for review @lkiesow @gregorydlogan . 

I added a method, which is now able to include multiple creators, publishers etc. ,if neccessary. So #1224 should be fixed as well.
