### PR TITLE
Cover image surrogate problem

### LINKED ISSUE #2499: Cover-image operation cannot handle multi-byte Unicdoe characters
If the event title contains multi-byte Unicode characters, the operation `cover-image` claims to finish successfully but will result in a black image and the following (not properly logged) message:

```
2021-04-16 00:25:27,600 | INFO  | (CoverImageWorkflowOperationHandlerBase:105) - Cover Image Workflow started for media package 'e8bfe29b-bce3-442d-8917-7c02b8c05cbe'                                                                        
About to transcoder source of type: org.apache.batik.apps.rasterizer.SVGConverterFileSource                                                                                                                                                   
org.apache.batik.transcoder.TranscoderException: null                                                                                                                                                                                         
Enclosed Exception:
Character reference "&#55357" is an invalid XML character.
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1001)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:717)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.rasterizeSvg(AbstractCoverImageService.java:283)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.generateCoverImageInternal(AbstractCoverImageService.java:176)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.process(AbstractCoverImageService.java:128)
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313)
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-16 00:25:37,631 | INFO  | (CoverImageWorkflowOperationHandlerBase:193) - Cover Image Workflow finished successfully for media package 'e8bfe29b-bce3-442d-8917-7c02b8c05cbe' within 17ms
```

Should happen with all Opencast 8 and Opencast 9 versions.

### PR DESCRIPTION
**Pull request by geichelberger**
During the transformation of the coverimage.xsl file, the emojis get escaped as surrogate pairs, which will result in an invalid XML/SVG file. (https://issues.apache.org/jira/browse/XALANJ-2617)
```

2021-11-19 21:52:28,614 | WARN  | (CoverImageWorkflowOperationHandlerBase:212) - No attachment with the flavor 'presenter/coverbackground' found in media package 'a8e7b9d6-9743-42fa-a4a6-fa3586e54c2d'
About to transcoder source of type: org.apache.batik.apps.rasterizer.SVGConverterFileSource
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Character reference "&#55357" is an invalid XML character.
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1001)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:717)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.rasterizeSvg(AbstractCoverImageService.java:289)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.generateCoverImageInternal(AbstractCoverImageService.java:175)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.process(AbstractCoverImageService.java:127)
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313)
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-11-19 21:52:33,635 | INFO  | (CoverImageWorkflowOperationHandlerBase:184) - Cover Image Workflow finished successfully for media package 'a8e7b9d6-9743-42fa-a4a6-fa3586e54c2d' within 25ms
```
Using the JDK internal version of Xalan successfully generates the SVG, but a batik bug appears.
coverimage-batik-1-7

After updating the batik dependency to the latest version 1.14 a new bug appears less severe than the others.

coverimage-batik-1-14

Maybe someone has an idea how to fix the last bug. I will investigate further, but the current result is already far better than the previous one, so I decided to create the PR.

Fixes #2499 (More or less)

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by geichelberger** [comment]
I accidentally filed the PR against the develop branch.

File: modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/AbstractCoverImageService.java [hunk 1]
```diff
@@ -233,32 +220,32 @@ protected static void transformSvg(Result svg, InputSource xmlSource, Document x
...
+    ClassLoader loader = thread.getContextClassLoader();
+    thread.setContextClassLoader(AbstractCoverImageService.class.getClassLoader());
     try {
+      Transformer transformer;
       // CHECKSTYLE:OFF
       // Xalan Transformer can't be configured safely
       // xslDoc is an already parsed Document
-      transformer = TransformerFactory.newInstance()
-              .newTransformer(new DOMSource(xslDoc));
+      transformer = TransformerFactory
```
Comment (gregorydlogan) [inline modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/AbstractCoverImageService.java:231]: This needs to use `SafeTransformerFactory` in the `common` module

**Review by gregorydlogan — CHANGES_REQUESTED** [review]

File: modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/AbstractCoverImageService.java (hunk 1 above)
Comment (geichelberger) [reply modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/AbstractCoverImageService.java:231]: That won't work, you have to call java functions during the XSL processing.

Comment (geichelberger) [reply modules/cover-image-impl/src/main/java/org/opencastproject/coverimage/impl/AbstractCoverImageService.java:231]: I tried to replace it with the SafeTransformerFactory version, but, as stated before, it won't work, and that's the reason why there is a comment above that line. Someone else tried that too.
