### PR TITLE
Sign urls in search rest service again

### LINKED ISSUE #5957: OC16 Seach Index does not support URL signing
From #5597 
"Notably, I did not include URL signing support with this. If this is a deal breaker we can work on it later."

This leads to Stream Security not working anymore.

In our case we have to disable stream security on our Wowza Server to play videos again with Opencast 16.

This is still documentented[1] but does not work anymore.

[1] https://docs.opencast.org/r/16.x/admin/#configuration/stream-security/stream-security-config/#configuration-of-wowza-url-signing

### PR DESCRIPTION
**Pull request by pselsa**
closes #5957

Since the search rest service doesnt sign urls anymore, the engage player wont work when signing is required for all urls. This PR adds url signing again to the search rest service and therefore reintroduces the `sign` parameter, having the default to true.

Previous PR that falsely targeted develop: https://github.com/opencast/opencast/pull/6082

### CODE REVIEW

File: modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java [hunk 1]
```diff
@@ -111,6 +114,10 @@ public class SearchRestService extends AbstractJobProducerEndpoint {
 
   private final Gson gson = new Gson();
 
+  private UrlSigningService urlSigningService;
+
+  private long expireSeconds = UrlSigningServiceOsgiUtil.DEFAULT_URL_SIGNING_EXPIRE_DURATION;
```
Comment (lkiesow) [inline modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java]: Setting this to `DEFAULT_URL_SIGNING_EXPIRE_DURATION` implies that this is configurable. Otherwise, you could also have used the constant in `findURLsAndSign(…)` directly. But this is never updated. Is this supposed to be configurable?

Comment (lkiesow) [reply modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java]: I'm merging it like this to get it into 16.3. It works and shouldn't hurt after all. I've filed this issue as https://github.com/opencast/opencast/issues/6099. If you can, it would be nice if you would take a look at that issue.

**Comment by lkiesow** [comment]
Ah, just when I wanted to hit merge :D
Will do a quick review and see that this makes it into 16.3 after CI is done.

File: modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java (hunk 1 above)
Comment (pselsa) [reply modules/search-service-impl/src/main/java/org/opencastproject/search/endpoint/SearchRestService.java]: Ok cool! You can assign the issue to me if you like ( i cannot do that myself)
