### PR TITLE
Fix#3164 assetmanager move to s3

### LINKED ISSUE #3164: asset-manager move to S3 duplicates identical files
**Describe the bug**

When the asset manager moves files into S3 using moveById, moveByDate or moveByIdAndDate multiple versions of episodes are moved to S3. This is done by creating a bunch of subjobs where each is moving a single version of an episode. These subjobs can run in parallel which can cause duplication of assets on S3 as multiple files with identical checksum can be moved at the same time.

expected behaviour would be that each file has a unique checksum on S3 and other files are mapped through the asset mapping table in the database.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Create multiple versions of an episode running workflows on local-filesystem
2. trigger the Rest Endpoint in /assets/moveById with the mpId and the target id "aws-s3"
3. be (un)lucky
4. Check the s3-bucket of the mediapackage and the Database

**Environment Information**
 - Opencast version 8 - *

### PR DESCRIPTION
**Pull request by ts23**
This fixes the asset manager move to s3 file duplication -  issue #3164 

This version combines the up to now individual moves of a media package on a by version to by mediapackage group.
when using:
* `moveById`  moves all versions of a mediapackage in order first to last within one job
* `moveByIdAndDate` moves all versions of a mediapackage within a date-range in order first to last within one job
* `moveByDate` moves all mediapackages in a date-range fetching them as individual mediapackages to then use `moveByIdAndDate` ... i.e. create a job for each mediapackage to then move all versions of that mediapackage which are in the date-range

### CODE REVIEW

**Comment by gregorydlogan** [comment]
CC @rute-santos @karendolan This might be relevant to your site, unclear.  Bad behaviour is triggered by use of moves *other than* move by ID and version.  Causes possible data duplication and DB inconsistency.

**Comment by rute-santos** [comment]
@gregorydlogan Thanks! We had the same problem some time ago, and had implemented a workaround. Looking forward to adopt @ts23  's fix when we upgrade!

File: modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerJobProducerTest.java [hunk 1]
```diff
@@ -156,6 +156,7 @@ public void testByDate() throws ServiceRegistryException {
     EasyMock.verify(sr);
   }
 
+  @Ignore
```
Comment (gregorydlogan) [inline modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerJobProducerTest.java]: Ignored test, which is also causing test failures when un-ignored :(

Now with logs:
```
[ERROR] Failures: 
[ERROR]   AssetManagerJobProducerTest.testInternalByDate:175 
  Unexpected method call ServiceRegistry.createJob("org.opencastproject.assetmanager", "MoveByIdAndDate", [remote-1-test, 63d89158-750f-44d2-803a-228b2890b08a, 1637094417909, 1637094418059], null, true, 0.1 (float)):
    ServiceRegistry.createJob("org.opencastproject.assetmanager", "MoveByIdAndVersion", [remote-1-test, 63d89158-750f-44d2-803a-228b2890b08a, 0], isNull(), true, 0.1 (float)): expected: 1, actual: 0
    ServiceRegistry.createJob("org.opencastproject.assetmanager", "MoveByIdAndVersion", [remote-1-test, 63d89158-750f-44d2-803a-228b2890b08a, 1], isNull(), true, 0.1 (float)): expected: 1, actual: 0
    ServiceRegistry.createJob("org.opencastproject.assetmanager", "MoveByIdAndVersion", [remote-1-test, c09d75db-b057-4b53-9d71-d538d24acd02, 0], isNull(), true, 0.1 (float)): expected: 1, actual: 0
    ServiceRegistry.createJob("org.opencastproject.assetmanager", "MoveByIdAndVersion", [remote-1-test, c09d75db-b057-4b53-9d71-d538d24acd02, 1], isNull(), true, 0.1 (float)): expected: 1, actual: 0
```

**Review by gregorydlogan — CHANGES_REQUESTED** [review]

File: modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerJobProducerTest.java (hunk 1 above)
Comment (ts23) [reply modules/asset-manager-impl/src/test/java/org/opencastproject/assetmanager/impl/AssetManagerJobProducerTest.java]: fixed in new commit
