### PR TITLE
Fix Google transcription service indefinite errors generation #1664 #2146

### LINKED ISSUE #1664: Google speech transcription service keeps generating errors when mediapackage deleted
Currently when a mediapackage with a scheduled transcription job is deleted before the transcription job ends (transcript attached to the mediapackage), the service will indefinitely generate errors as it is not able to find the mediapackage.

Correct behaviour: transcription should stop trying to attach transcript to mediapackage if it doesn't exist and inform the user.

[Issue reported by Carter Wallace. ](https://groups.google.com/a/opencast.org/forum/#!topic/users/hKsO26lLTuE)

### PR DESCRIPTION
**Pull request by tyfranck**
If media package has been deleted or Google speech to text APIs encounters a problem, The Google transcription service will keep generating errors without stopping.
This pull request addresses those issues.

This fixes  #1664  #2146

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
Would it make sense to bring this into 9.x?
It seems like a bug fix.

**Comment by tyfranck** [comment]
Yes and probably 8.x as well if still supported.

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java [hunk 1]
```diff
@@ -866,6 +870,37 @@ private String buildResultsFileName(String jobId) {
...
+      // set a time limit based on video duration and maximum processing time
+      if (database.findByJob(jobId).getDateCreated().getTime() + database.findByJob(jobId).getTrackDuration()
+              + (completionCheckBuffer + maxProcessingSeconds) * 1000 < System.currentTimeMillis()) {
+        return true;
+      }
+    } catch (Exception e) {
+      logger.error(String.format("ERROR while calculating transcription request expiration for job: %s", jobId), e);
+    }
+    return false;
+  }
```
Comment (karendolan) [inline modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:906]: Would it make sense to return true when there is an ERROR level error? Or is it useful to allow manual intervention to troubleshot the issue before cancelling the transcript? I'm wonder why it is better to leave the job in perpetual non-expired state during an exception. For example, maybe an issue with the database connection at that point or the transcription job has not been fully at this point.

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java [hunk 2]
```diff
@@ -1014,7 +1048,7 @@ public void run() {
             // Apply workflow to attach transcripts
```
Comment (karendolan) [inline modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:1067]: "Jobs that get here have state TranscriptionCompleted [... or had an IOException]"

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java [hunk 3]
```diff
@@ -866,6 +870,37 @@ private String buildResultsFileName(String jobId) {
...
+        String token = getRefreshAccessToken();
+        deleteStorageFile(mpId, token);
+      } catch (Exception ex) {
+        logger.warn(String.format("could not delete file %s.%s from Google cloud storage", mpId, defaultEncoding), ex);
+      }
+      // Send notification email
+      sendEmail("Transcription ERROR", String.format("%s(media package %s, job id %s).", message, mpId, jobId));
+    } catch (Exception e) {
+      logger.error(String.format("ERROR while deleting transcription job: %s", jobId), e);
+    }
```
Comment (karendolan) [inline modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:890]: It might be helpful to put the sendMail in a finally block to include the general Exception, or, condense into one try-catch block.

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java [hunk 4]
```diff
@@ -1043,8 +1077,13 @@ private String startWorkflow(String mpId, String wfDefId, Map<String, String> pa
...
-      logger.warn("Media package {} has not been archived yet.", mpId);
+      if (!hasTranscriptionRequestExpired(jobId)) {
+        // Media package not archived but still within completion time? Skip until next time.
+        logger.warn("Media package {} has not been archived yet. Skipped.", mpId);
+      } else {
+        // Close transcription job and email admin
+        cancelTranscription(jobId, "Transcription job canceled, archived media package not found");
+      }
       return null;
     }
```
Comment (karendolan) [inline modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:1109]: It's too bad that the workflow service is not (or cannot be?) queried here to verify that the mpId still exists when the asset manager has no knowledge of the mpId.  For example, when the event is deleted before Google transcript is attached, a 5 hour timeout plus length of video plus buffer has to be waited through before cancelling the transcript job. .... it might be useful to include the countdown in that Skipped log line. For example 
```
logger.warn("Media package {} has not been archived yet or has been deleted. Will keep trying for {} more minutes before cancelling transcript job {}.", mpId, getRemainingTranscriptionExpireTimeInMin(jobId), jobId);
```

Comment (karendolan) [reply modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:1109]: As a future feature, it might be worth adding a listener for deleted events to the transcript service so it can cancel out jobs when the event is deleted before the transcript is attached.

For example, here the event delete is sent to ActiveMQ but transcription service doesn't listen to that event.
```
2021-01-27T10:18:19,425 | INFO  | (AssetManagerWithMessaging:221) - Send delete message for episode 45b480a8-ace5-47b8-abee-33744cacb5fe to ActiveMQ
2021-01-27T10:31:35,944 | INFO  | (GoogleSpeechTranscriptionService:591) - Recognitions job 4747558756009661662 has been found, completed status true
```

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java [hunk 5]
```diff
@@ -604,6 +604,10 @@ boolean getAndSaveJobResults(String jobId) throws TranscriptionServiceException,
     } catch (TranscriptionServiceException e) {
       throw e;
     } catch (Exception e) {
+      if (hasTranscriptionRequestExpired(jobId)) {
+        // Cancel the job and inform admin
+        cancelTranscription(jobId, "Transcription job canceled due to errors");
+      }
```
Comment (karendolan) [inline modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:611]: It would help to log an INFO that the job is being cancelled, in addition to the email. Since there are 5 hours of retry logs, this would be the one log bringing the logs to closure for this transcription job. 

Also, IMHO, it would help to add "Google Transcription" to the cancelTranscription email text, since the email message is coming from the Google Transcription service (vs IBM Watson Transcription service)

**Comment by karendolan** [comment]
Hi @tyfranck  the pull works in that it waits for 5 hours + buffer + video duration before cancelling the transcription job. IMHO, 80% of the problem is that the transcription service does not subscribe to delete-event events (or to ask the workflow service if it knows the mpId when asset manager doesn't). But, that's a bigger code change. 

My biggest comment on this pull is to add an INFO log when doing the cancel. Also, is there an Opencast docs section for Google Transcription that can describe the transcript expire delay config? Feel free to comment back a yes or no regarding my comments :).

**Comment by tyfranck** [comment]
Hi @karendolan, thanks for reviewing this. I'll look into your suggestion of transcription service subscribing to delete-event. Do you know anywhere in opencast where that is done so I can re-use? It's obviously bigger change and not part of this PR but I'll investigate for future updates. 
Note that the `5 hours`  and the `buffer` can be changed to any duration in the config.

I'll add an INFO log and update Google transcription docs accordingly for this PR, you're right about that :-).

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java (hunk 1 above)
Comment (tyfranck) [reply modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:906]: yes, returning `true` will avoid perpetual non-expired state.

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java (hunk 4 above)
Comment (tyfranck) [reply modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:1109]: I like the idea of count down, I'll try to add it.
I'll add the second part of your comment in future improvements.

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java (hunk 5 above)
Comment (tyfranck) [reply modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:611]: Agree

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java (hunk 3 above)
Comment (tyfranck) [reply modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:890]: fixed

File: modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java (hunk 4 above)
Comment (tyfranck) [reply modules/transcription-service-google-speech-impl/src/main/java/org/opencastproject/transcription/googlespeech/GoogleSpeechTranscriptionService.java:1109]: Count down now added

**Review by karendolan — APPROVED** [review]
Looks good. A delete event watcher feature for some future day.
