### PR TITLE
Fixes removing a series from an event

### LINKED ISSUE #1721: Removing a series from an event does not work
**Describe the bug**
Given that an event is part of a series. Removing the series does not work.

**To Reproduce**
1. Create a series in Opencast
2. Upload an event and choose the previously created series, wait for processing
3. Go to the metadata tab and edit the series, choose in the drop down menu: -- No option selected --
4. Wait for the green checkmark
5. Close the event details
6. The event should now be without a series, however, the previous series is still assigned to the event

**Environment Information**
 - OS: Arch Linux
 - Browser: Firefox 78
 - Opencast 8 (stable.opencast.org at 29.07.2020)

### PR DESCRIPTION
**Pull request by Arnei**
Resolves #1721.

The frontend attempts to save "no option selected" as `null` to the backend. The backend does not accept `null` values. Instead the frontend should save "no option" as the empty string.

This corrects `null` to the empty string when submitting. A rather crude fix, but I could not figure out why AngularJS fails to set the correct value in this case.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/#development-process/#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

File: modules/admin-ui-frontend/app/scripts/shared/directives/editableSingleSelectDirective.js [hunk 1]
```diff
@@ -172,6 +172,11 @@ angular.module('adminNg.directives')
         // Wait until the change of the value propagated to the parent's metadata object.
         scope.submitTimer = $timeout(function () {
           if (scope.params.value !== scope.oldValue) {
+            // Selecting "no option" will wrongly set param to `null` instead of the empty string.
+            // The backend will ignore `null` submissions, so we set it to the empty string instead.
+            if (scope.params.value === null) {
+              scope.params.value = "";
```
Comment (lkiesow) [inline modules/admin-ui-frontend/app/scripts/shared/directives/editableSingleSelectDirective.js]:
```suggestion
              scope.params.value = '';
```
