### PR TITLE
Changed inbox behaviour for additional files for scheduled events

### LINKED ISSUE #3649: Inbox Scanner assignment of scheduled events: issue when ingesting >1 recordings for same scheduled event
**Describe the bug**
If more that one recordings are sequentially copied in the inbox folder for the same scheduled event, there are issues with ingesting (usually eg in case of 2 files, the second one hangs in the inbox).
This is a frequent case as lecturers often take a break or they run a short test recording at the beginning of a lecture.

Probably this issue is related to this one:
https://github.com/opencast/opencast/issues/2276

**To Reproduce**
1. Schedule an event that lasts 2 hours
2. copy a file that corresponds to the first part of this event to the inbox folder
3. copy a second file that corresponds to the second half of the same scheduled event to the inbox folder

**Suggested solution**
Automatic ingesting of scheduled events should allow for more than one parts of the same event to be ingested; this could be done by:
– before ingesting, check status of respective media package (maybe wf running?)
– if status "scheduled" then ingest as usual
– if status eg "running" then copy the event to a new media package and ingest the new media to this new media package (named as "... – part 2", "...–part n", for example

### PR DESCRIPTION
**Pull request by Arnei**
Resolves #3649

Previously, additional files for a scheduled event to the inbox would overwrite the previous event or cause an exception in case a workflow was currently running on the scheduled event. Now, new events are created for additional files instead.

Unfortunately I did not find a (reasonably easy) way to number the new events as requested in the linked issue. For now, new events are named after the pattern "originalTitle - newEventId". 

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

File: modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java [hunk 1]
```diff
@@ -239,6 +249,31 @@ public RetriableIngestJob call() {
...
+                  try {
+                    Recording recordingState = schedulerService.getRecordingState(id);
+                    if (recordingState.getState().equals(UPLOAD_FINISHED)) {
+                      mediaPackage = (MediaPackage) mediaPackage.clone();
+                      Id newId = IdImpl.fromUUID();
+                      mediaPackage.setIdentifier(newId);
+
+                      // Update dublincore title
+                      try {
+                        String newTitle = mediaPackage.getTitle() + " - " + newId;
```
Comment (lkiesow) [inline modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java]: Some insider knowledge: Never try getting correct metadata from the media package. Always extract it from the Dublin Core catalog. My first test ended up like this:

Screenshot from 2022-04-20 16-40-36

Comment (lkiesow) [reply modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java]: Maybe something like:

```diff
@@ -255,15 +255,17 @@ public class Ingestor implements Runnable {
   try {
     Recording recordingState = schedulerService.getRecordingState(id);
     if (recordingState.getState().equals(UPLOAD_FINISHED)) {
+      var referenceId = mediaPackage.getIdentifier().toString();
       mediaPackage = (MediaPackage) mediaPackage.clone();
-      Id newId = IdImpl.fromUUID();
-      mediaPackage.setIdentifier(newId);
+      mediaPackage.setIdentifier(IdImpl.fromUUID());

       // Update dublincore title
       try {
-        String newTitle = mediaPackage.getTitle() + " - " + newId;
         DublinCoreCatalog dc = DublinCoreUtil.loadEpisodeDublinCore(workspace, mediaPackage).get();
+        var newTitle = dc.get(DublinCore.PROPERTY_TITLE).get(0).getValue()
+            + " (" + Instant.now().getEpochSecond() + ")";
         dc.set(DublinCore.PROPERTY_TITLE, newTitle);
+        dc.set(DublinCore.PROPERTY_REFERENCES, referenceId);
         mediaPackage = updateDublincCoreCatalog(mediaPackage, dc);
         mediaPackage.setTitle(newTitle);
       } catch (Exception e) {
```

This…
- uses the DC title
- adds the original event as reference
- switches from the very long UUID to the ingest time (as unix timestamp) which will at least give you an order for the ingested events

**Review by lkiesow — CHANGES_REQUESTED** [review]

File: modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java (hunk 1 above)
Comment (Arnei) [reply modules/ingest-service-impl/src/main/java/org/opencastproject/ingest/scanner/Ingestor.java]: Very good suggestions, should be implemented now.

**Review by lkiesow — APPROVED** [review]
Now this looks better.
Screenshot from 2022-04-22 13-03-01

**Comment by ypatios** [comment]
It seems that the newly created additional events involve a duplication step which copies the initial recording in the new media package. This has as a result that every new part of the same event contains media files of the same flavor (which causes problems in the processing/publishing workflows).
The initial media file(s) should not be included in any of the additional parts. Thus, I regard this as a bug. Right?
Should I reopen the original issue or create a new one?

**Comment by lkiesow** [comment]
A second event will inherit all data already in the asset manager for that event.
We could only filter that to e.g. remove media if we wanted to.

Please file a new issue for that. I only noticed it by accident here.

**Comment by ypatios** [comment]
Yes, it would make sense to omit the initial recording.
I'll create a new issue. Thanks
