### PR TITLE
Fixed publication pop-overs overlaying each other

### LINKED ISSUE #2519: Publication links in admin interface not always closing
Clicking on another publication link in the admin interface while one is still open will cause multiple windows to open and potentially overlap.

https://user-images.githubusercontent.com/1008395/115154819-18102700-a07d-11eb-9334-f3e102ee05ec.mp4

Happening in Opencast 9.3 and develop (2021-04-18).

### PR DESCRIPTION
**Pull request by Arnei**
Circumvents the problem by closing all other publication pop-overs when opening a new one. This means the pop-overs can potentially still overlap with other elements (e.g. the filter dropdown), but maybe that's not a bug but a feature.

Resolves #2519

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

File: modules/admin-ui-frontend/app/scripts/modules/events/controllers/touchController.js [hunk 1]
```diff
@@ -24,6 +24,7 @@ angular.module('adminNg.controllers')
 .controller('TouchCtrl', ['$scope', '$document',
   function ($scope, $document) {
     $scope.openPopup = function(id) {
+     $scope.clearPopup();
```
Comment (lkiesow) [inline modules/admin-ui-frontend/app/scripts/modules/events/controllers/touchController.js]:
```suggestion
      $scope.clearPopup();
```
