### PR TITLE
Check if encoding profile exist for imageToVideo Operation

### LINKED ISSUE #3465: Partial-Import-WOH without import encoding leads to non clear exception
**Describe the bug**
With Opencast 11 the encoding Profiles for Partial Import are not installed automatically.
If you use Partial Import without installing them,
The Workflow fails without any appropriate error message what`s wrong. 

**To Reproduce**
1. Use Partial Import in a Workflow
2. encodingprofile import.silent ist not installt

**Environment Information**
 - Opencast version with release > 11.x

### PR DESCRIPTION
**Pull request by CGreweling**
This Pullrequest log a proper ERROR if the Encoding Profile is missing in imageToVideo Operation.

This fixes #3465

### Your pull request should…

* [ x] have a concise title
* [ x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ x] pass automated tests
* [ x] have a clean commit history
* [ x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by CGreweling** [comment]
I hope i have done the Opencast "Exception thing" the right way here.   
Any hints if not are very welcome.

File: modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java [hunk 1]
```diff
@@ -996,6 +996,10 @@ public Job imageToVideo(Attachment sourceImageAttachment, String profileId, doub
           MediaPackageException {
     try {
       final EncodingProfile profile = profileScanner.getProfile(profileId);
+      if (profile == null) {
+        logger.error("Encoding profile {} not found", profileId);
+        throw new MediaPackageException("No encoding set");
```
Comment (lkiesow) [inline modules/composer-ffmpeg/src/main/java/org/opencastproject/composer/impl/ComposerServiceImpl.java]: This will lead to a stack trace with a non-helpful message and a separate error log entry. Why not just have a proper error message in the Exception?

```suggestion
        throw new MediaPackageException(String.format("Encoding profile %s not found", profileId));
```

**Review by lkiesow — CHANGES_REQUESTED** [review]

**Review by lkiesow — APPROVED** [review]

**Comment by lkiesow** [comment]
This looks good and can be merged, but in #3465, you say this effects Opencast 11. Is this intended to go into `r/11.x`? Or is `develop` correct?

**Comment by CGreweling** [comment]
Yes right. This is also a Problem for OC 11. 
Waht would be the right way here.
Repoint this to 11, or close this PR and reopen a new one againts 11?

**Comment by lkiesow** [comment]
If you click on `Edit` right next to the title, you can change the target branch of this pull request. If you already based this on `r/11.x`, that's all you need to do. If not, `git rebase -i r/11.x` is an easy way of basing this on `r/11.x`. Let me know if you need help with that.
